name: Renovate

on:
  schedule:
    - cron: '0 * * * 0'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Renovate
        uses: renovatebot/github-action@v32.194.4
        env:
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
